CREATE TABLE IF NOT EXISTS app_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name VARCHAR(70) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  password_hash VARCHAR(128) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS friendship (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_id BIGINT NOT NULL REFERENCES app_user(id),
  addressee_id BIGINT NOT NULL REFERENCES app_user(id),
  status VARCHAR(12) NOT NULL CHECK (status IN ('PENDING','ACCEPTED','DECLINED')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(requester_id, addressee_id)
);
CREATE TABLE IF NOT EXISTS catalog_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  category VARCHAR(60) NOT NULL,
  suggested_price DECIMAL(12,2) NOT NULL CHECK (suggested_price > 0)
);
CREATE TABLE IF NOT EXISTS wish_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id BIGINT NOT NULL REFERENCES app_user(id),
  title VARCHAR(120) NOT NULL,
  note VARCHAR(500),
  price DECIMAL(12,2) NOT NULL CHECK (price > 0),
  status VARCHAR(12) DEFAULT 'OPEN' CHECK (status IN ('OPEN','FUNDED')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS contribution (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wish_item_id BIGINT NOT NULL REFERENCES wish_item(id),
  buyer_id BIGINT NOT NULL REFERENCES app_user(id),
  amount DECIMAL(12,2) NOT NULL CHECK (amount > 0),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS notification (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id BIGINT NOT NULL REFERENCES app_user(id),
  message VARCHAR(500) NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
MERGE INTO catalog_item (id, name, category, suggested_price) KEY(id) VALUES
 (1, 'Noise-cancelling headphones', 'Tech', 3200.00),
 (2, 'Watercolor starter set', 'Creative', 850.00),
 (3, 'Weekend book bundle', 'Books', 650.00),
 (4, 'Yoga mat', 'Wellness', 900.00),
 (5, 'Coffee grinder', 'Home', 1800.00);
